# NLP

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import seaborn as sns

In [4]:
df = pd.read_csv("spam.csv" , encoding = "latin1")

In [5]:
df.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [6]:
df.shape

(5572, 5)

In [7]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [8]:
df = df[["v1", "v2"]]

In [9]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.rename(columns={"v1": "label", "v2":"message"}, inplace = True)

In [11]:
df.head(2)

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...

In [12]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(403)

In [14]:
df.drop_duplicates()

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [15]:
df.duplicated().sum()

np.int64(403)

In [16]:
print(f"spam message : {(df["label"] == "spam").sum()}")

spam message : 747

In [17]:
print(f"ham message : {(df["label"] == "ham").sum()}")

ham message : 4825

In [18]:
print("FREE ENTRY of concert".lower())

free entry of concert

In [19]:
df["message"] = df["message"].str.lower()

In [20]:
df.head()

  label                                            message
0   ham  go until jurong point, crazy.. available only ...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham  u dun say so early hor... u c already then say...
4   ham  nah i don't think he goes to usf, he lives aro...

In [21]:
import re

In [22]:
example = "free entry in 2 a weklk !!!! hurrah you won fa tesxt 7354636"

In [23]:
example_clean = re.sub(r"[^a-z \s]", "", example)

In [24]:
print(example_clean)

free entry in  a weklk  hurrah you won fa tesxt

In [25]:
df['message'] = df['message'].apply(lambda x: re.sub(r'[^a-z \s]', '', x))

In [26]:
df.head()

  label                                            message
0   ham  go until jurong point crazy available only in ...
1   ham                            ok lar joking wif u oni
2  spam  free entry in  a wkly comp to win fa cup final...
3   ham        u dun say so early hor u c already then say
4   ham  nah i dont think he goes to usf he lives aroun...

In [27]:
import nltk

In [28]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\cxash\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [29]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\cxash\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [30]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\cxash\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [31]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [32]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\cxash\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [33]:
sample = "hello all how are you doing today"

In [34]:
sent_token=sent_tokenize(sample)

In [35]:
sample_token = word_tokenize(sample)

In [36]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\cxash\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [37]:
print(sample_token )

['hello', 'all', 'how', 'are', 'you', 'doing', 'today']

In [38]:
from nltk.corpus import stopwords

In [39]:
stopwords = set(stopwords.words('english'))

In [40]:
df['message'] = df['message'].apply(lambda x : " ".join(
    [words for words in word_tokenize(x) 
     if words not in stopwords]
))

In [41]:
print(df["message"][2])

free entry wkly comp win fa cup final tkts st may text fa receive entry questionstd txt ratetcs apply overs

In [42]:
import nltk
from nltk.stem import PorterStemmer

In [43]:
# Stemmer = PorterStemmer()
stemmer = PorterStemmer()

In [44]:
# df['message'] = df['message'].apply(
#     lambda x : " ".join([stemmer.stem(word) for word in x.split()])
# )
df['message'] = df['message'].apply(
    lambda x: " ".join([stemmer.stem(word) for word in x.split()])
)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [46]:
x = df["message"]

In [47]:
y = df["label"]

In [48]:
tfidf = TfidfVectorizer(max_features=3000)

In [49]:
x_vec = tfidf.fit_transform(x)

In [50]:
x_vec.shape[1]

3000

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
x_train,x_test,y_train,y_test = X_train, X_test, Y_train, Y_test = train_test_split(
    x_vec,
    y,
    test_size=0.20,
    random_state=42
)

In [53]:
from sklearn.naive_bayes import MultinomialNB

In [54]:
model = MultinomialNB()

In [55]:
model.fit(x_train,y_train)

MultinomialNB()

In [56]:
y_pred = model.predict(x_test)

In [57]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [58]:
accuracy = accuracy_score(y_test, y_pred)

In [59]:
print(accuracy_score)

<function accuracy_score at 0x0000017E41DCECA0>

In [60]:
cm = confusion_matrix(y_test, y_pred)

In [61]:
cm

array([[965,   0],
       [ 26, 124]])

In [62]:
def predict_message (message):
    msg = message.lower()
    msg = re.sub(r'[^a-z \s]', " ", msg)
    token = word_tokenize(msg)
    token = [w for w in token
            if w not in stopwords]
    tokens = [stemmer.stem(w) for w in token]
    clean_msg = " ".join(tokens)
    vec = tfidf.transform([clean_msg])
    result = model.predict(vec)[0]
    prob= model.predict(vec)[0]
    return result, prob

In [63]:
text_msg = """congratulations you won a lottery of 100000 rs click on the clink to claim your winning price.

    URgent click the link to claim you Money
    
    """

In [64]:
predict_message(text_msg)

(np.str_('spam'), np.str_('spam'))